[package]
name = "nakatoshi"
version = "0.1.0"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"
description = "Bitcoin vanity address generator"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ndelvalle/nakatoshi"
repository = "https://github.com/ndelvalle/nakatoshi"
keywords = ["bitcoin", "address", "vanity", "vanity-address"]
categories = ["command-line-utilities"]

[dependencies]
bitcoin = "0.23.0"
clap = "2.33.1"
time = "0.2.16"
rayon = "1.3.1"
getrandom = "0.1.14"
secp256k1 = "0.17.2"
serde = "1.0.114"
serde_json = "1.0.56"
spinners = "1.2.0"
num_cpus = "1.13.0"
